#pragma once

extern "C" __declspec(dllexport) int curl_easy_cleanup() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_duphandle() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_escape() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_getinfo() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_init() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_option_by_id() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_option_by_name() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_option_next() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_pause() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_perform() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_recv() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_reset() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_send() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_setopt() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_strerror() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_unescape() {     return 0; }
extern "C" __declspec(dllexport) int curl_easy_upkeep() {     return 0; }
extern "C" __declspec(dllexport) int curl_escape() {     return 0; }
extern "C" __declspec(dllexport) int curl_formadd() {     return 0; }
extern "C" __declspec(dllexport) int curl_formfree() {     return 0; }
extern "C" __declspec(dllexport) int curl_formget() {     return 0; }
extern "C" __declspec(dllexport) int curl_free() {     return 0; }
extern "C" __declspec(dllexport) int curl_getdate() {     return 0; }
extern "C" __declspec(dllexport) int curl_getenv() {     return 0; }
extern "C" __declspec(dllexport) int curl_global_cleanup() {     return 0; }
extern "C" __declspec(dllexport) int curl_global_init() {     return 0; }
extern "C" __declspec(dllexport) int curl_global_init_mem() {     return 0; }
extern "C" __declspec(dllexport) int curl_global_sslset() {     return 0; }
extern "C" __declspec(dllexport) int curl_maprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_mfprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_addpart() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_data() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_data_cb() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_encoder() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_filedata() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_filename() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_free() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_headers() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_init() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_name() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_subparts() {     return 0; }
extern "C" __declspec(dllexport) int curl_mime_type() {     return 0; }
extern "C" __declspec(dllexport) int curl_mprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_msnprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_msprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_add_handle() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_assign() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_cleanup() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_fdset() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_info_read() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_init() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_perform() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_poll() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_remove_handle() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_setopt() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_socket() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_socket_action() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_socket_all() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_strerror() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_timeout() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_wait() {     return 0; }
extern "C" __declspec(dllexport) int curl_multi_wakeup() {     return 0; }
extern "C" __declspec(dllexport) int curl_mvaprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_mvfprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_mvprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_mvsnprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_mvsprintf() {     return 0; }
extern "C" __declspec(dllexport) int curl_pushheader_byname() {     return 0; }
extern "C" __declspec(dllexport) int curl_pushheader_bynum() {     return 0; }
extern "C" __declspec(dllexport) int curl_share_cleanup() {     return 0; }
extern "C" __declspec(dllexport) int curl_share_init() {     return 0; }
extern "C" __declspec(dllexport) int curl_share_setopt() {     return 0; }
extern "C" __declspec(dllexport) int curl_share_strerror() {     return 0; }
extern "C" __declspec(dllexport) int curl_slist_append() {     return 0; }
extern "C" __declspec(dllexport) int curl_slist_free_all() {     return 0; }
extern "C" __declspec(dllexport) int curl_strequal() {     return 0; }
extern "C" __declspec(dllexport) int curl_strnequal() {     return 0; }
extern "C" __declspec(dllexport) int curl_unescape() {     return 0; }
extern "C" __declspec(dllexport) int curl_url() {     return 0; }
extern "C" __declspec(dllexport) int curl_url_cleanup() {     return 0; }
extern "C" __declspec(dllexport) int curl_url_dup() {     return 0; }
extern "C" __declspec(dllexport) int curl_url_get() {     return 0; }
extern "C" __declspec(dllexport) int curl_url_set() {     return 0; }
extern "C" __declspec(dllexport) int curl_version() {     return 0; }
extern "C" __declspec(dllexport) int curl_version_info() {     return 0; }
